# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Lerna
    init: |
      yarn global add lerna
      yarn run lerna bootstrap
      yarn run lerna run build
    command: echo 'start script'
